/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;
import Clases.Patient;
import Controladores.PatientG;
import Controladores.ConnectDB;
import java.sql.Connection;
import javax.swing.JOptionPane;



/**
 *
 * @author Felip
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accept = new javax.swing.JButton();
        register = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        insertUser = new javax.swing.JFormattedTextField();
        insertPass = new javax.swing.JPasswordField();
        user = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        blan = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        grey = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        accept.setBackground(new java.awt.Color(51, 51, 51));
        accept.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        accept.setForeground(new java.awt.Color(255, 255, 255));
        accept.setText("LOGIN");
        accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptActionPerformed(evt);
            }
        });
        getContentPane().add(accept, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 270, -1, -1));

        register.setBackground(new java.awt.Color(51, 51, 51));
        register.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        register.setForeground(new java.awt.Color(255, 255, 255));
        register.setText("REGISTER");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        getContentPane().add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, -1, -1));

        exit.setBackground(new java.awt.Color(51, 51, 51));
        exit.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, -1, -1));
        getContentPane().add(insertUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 240, 20));

        insertPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertPassActionPerformed(evt);
            }
        });
        getContentPane().add(insertPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 240, -1));

        user.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        user.setText("USER:");
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 60, 40));

        password.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        password.setText("PASSWORD:");
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 90, 40));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ingrese sus datos:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(99, 99, 99))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 370, 40));

        blan.setIcon(new javax.swing.ImageIcon("C:\\Users\\Felip\\OneDrive\\Imágenes\\blacn.png")); // NOI18N
        blan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(blan, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 480, 240));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Felip\\OneDrive\\Imágenes\\Login200.jpg")); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jLabel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, -1));

        grey.setIcon(new javax.swing.ImageIcon("C:\\Users\\Felip\\OneDrive\\Imágenes\\gray.jpg")); // NOI18N
        grey.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(grey, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 600, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void acceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptActionPerformed
        ConnectDB conn = new ConnectDB();
        Connection link = conn.Connect();
        PatientG patient = new PatientG();
        if(patient.Search(link, insertUser.getText())!=null){
            conn.CloseConection();
            MainWindow main = new MainWindow();
            main.setVisible(true);
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(null, "Usuario o contrase;a incorrectos");
            conn.CloseConection();
        }
    }//GEN-LAST:event_acceptActionPerformed

    private void insertPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertPassActionPerformed
        // TODO add your handling code hre:
    }//GEN-LAST:event_insertPassActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        register res = new register();
        res.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_registerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accept;
    private javax.swing.JLabel blan;
    private javax.swing.JButton exit;
    private javax.swing.JLabel grey;
    private javax.swing.JPasswordField insertPass;
    private javax.swing.JFormattedTextField insertUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel password;
    private javax.swing.JButton register;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
