/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Clases.Patient;
import Controladores.ConnectDB;
import Controladores.PatientG;
import Controladores.PhysiqueC;
import java.sql.Connection;
import java.sql.Date;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Felip
 */
public class perfil extends javax.swing.JFrame {
    int rut;

    public int getRut() {
        return rut;
    }

    public void setRut(int rut) {
        this.rut = rut;
        
        mostrar();
    }
    
    /**
     * Creates new form perfil
     */
    public perfil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        RUT = new javax.swing.JPanel();
        nombre = new javax.swing.JLabel();
        lastName = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        height = new javax.swing.JLabel();
        weight = new javax.swing.JLabel();
        bmi = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo.setBackground(new java.awt.Color(102, 255, 153));

        RUT.setBackground(new java.awt.Color(255, 255, 255));

        nombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        nombre.setText("Nombre:");

        lastName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lastName.setText("Apellido:");

        date.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        date.setText("Fecha de Nacimiento:");

        height.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        height.setText("Altura:");

        weight.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        weight.setText("Peso:");

        bmi.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bmi.setText("BMI:");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Rut:");

        email.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        email.setText("Email:");

        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jButton1.setText("DELETE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RUTLayout = new javax.swing.GroupLayout(RUT);
        RUT.setLayout(RUTLayout);
        RUTLayout.setHorizontalGroup(
            RUTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RUTLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RUTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RUTLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(back)
                        .addGap(19, 19, 19))
                    .addGroup(RUTLayout.createSequentialGroup()
                        .addComponent(height)
                        .addGap(170, 170, 170)
                        .addComponent(weight)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RUTLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(RUTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bmi)
                    .addComponent(jButton1))
                .addGap(27, 27, 27))
            .addGroup(RUTLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(RUTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(date)
                    .addGroup(RUTLayout.createSequentialGroup()
                        .addGroup(RUTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(nombre))
                        .addGap(170, 170, 170)
                        .addGroup(RUTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lastName)
                            .addComponent(email))))
                .addContainerGap(220, Short.MAX_VALUE))
        );
        RUTLayout.setVerticalGroup(
            RUTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RUTLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back)
                .addGap(16, 16, 16)
                .addGroup(RUTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre)
                    .addComponent(lastName))
                .addGap(56, 56, 56)
                .addGroup(RUTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(email))
                .addGap(61, 61, 61)
                .addComponent(date)
                .addGap(101, 101, 101)
                .addGroup(RUTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(height)
                    .addComponent(weight)
                    .addComponent(bmi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RUT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RUT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void mostrar(){
        ConnectDB conn = new ConnectDB();
        Connection link = conn.Connect();
        PatientG patient = new PatientG();
        PhysiqueC phyC = new PhysiqueC();
        Patient pat = new Patient();
        pat = patient.Search(link, getRut());
        
        
        if(pat != null){
            
            nombre.setText("Nombre: "+pat.getFirst_name());
            lastName.setText("Apellido: "+pat.getLast_name());
            jLabel7.setText("Rut: "+String.valueOf(pat.getRut()));
            Date fechaNacimiento = pat.getBirth_date();
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            date.setText("Fecha de nacimiento: "+formato.format(fechaNacimiento));
            email.setText("Correo Electronico: "+pat.getEmail());
            //weight.setText(String.valueOf(pat.getPhysical_state().getWeight()));
            //height.setText(String.valueOf(pat.getPhysical_state().getHeight()));
            //bmi.setText(String.valueOf(pat.getPhysical_state().getBmi()));
        }
        else{
            JOptionPane.showMessageDialog(null, "Error al cargar los datos");
        }
    }
    
    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        MainWindow log = new MainWindow();
        log.setRut(getRut());
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ConnectDB conn = new ConnectDB();
        Connection link = conn.Connect();
        PatientG patient = new PatientG();
        Patient pat = new Patient();
        
        if(patient.Delete(conn.Connect(), getRut())==true){
            JOptionPane.showMessageDialog(null, "Se ha eliminado exitosamente");
            this.dispose();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new perfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel RUT;
    private javax.swing.JButton back;
    private javax.swing.JLabel bmi;
    private javax.swing.JLabel date;
    private javax.swing.JLabel email;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel height;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lastName;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel weight;
    // End of variables declaration//GEN-END:variables
}
